train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: Tr/mnt/nas/b103/zhanghonghu1/data/MESO/grapes_meso_3km_T2m_1200_13_653_min_max_nor.npz
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_min: 1
      scale_max: 4
      augment: false
      sample_q: 2304
  batch_size: 1

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: Te/mnt/nas/b103/zhanghonghu1/data/MESO/grapes_meso_3km_T2m_1200_13_653_min_max_nor.npz
  wrapper:
    name: val-sr-implicit-downsampled
    args:
      scale_min: 1
      scale_max: 4
  batch_size: 1

model:
  name: lte
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    imnet_spec:
      name: mlp
      args:
        out_dim: 1
        hidden_list: [256,256,256]
    hidden_dim: 256

optimizer:
  name: adam
  args:
    lr: 1.e-4

multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_max: 2000
epoch_val: 1
epoch_save: 10

resume: ./save/_train_edsr-baseline-lte/epoch-last.pth
       