train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: Tr/mnt/hdd1/zhanghonghu1/DATA/MeteoNet_2018/v5_nor
  wrapper:
    name: sr-implicit-downsampled
    args:
      sta_num_gt: 100
  batch_size: 1

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: Te/mnt/hdd1/zhanghonghu1/DATA/MeteoNet_2018/v5_nor
  wrapper:
    name: sr-implicit-downsampled
    args:
      sta_num_gt: 60
  batch_size: 1

model:
  name: lte
  args:
    encoder_spec:
      name: amsd
      args:
        no_upsampling: true
    imnet_spec:
      name: mlp
      args:
        out_dim: 1
        hidden_list: [256,256,256]
    hidden_dim: 256

optimizer:
  name: adam
  args:
    lr: 1.e-4

multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_max: 1000
epoch_val: 1
epoch_save: 1

resume: ./save/_train_edsr-baseline-lte/epoch-last.pth
